# Generated by Django 4.2 on 2023-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Image')),
                ('Descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
