# Generated by Django 4.2 on 2023-07-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(verbose_name='Rut')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('rol', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='paginas',
            name='Descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
