# Generated by Django 4.2 on 2023-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_proyecto', '0002_users_alter_paginas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rol',
            field=models.IntegerField(verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rut',
            field=models.CharField(max_length=100, verbose_name='Rut'),
        ),
    ]
