# Generated by Django 4.2 on 2023-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_proyecto', '0003_alter_users_rol_alter_users_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNueva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=13, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('rol', models.IntegerField(verbose_name='Rol')),
            ],
        ),
    ]
